import os

from traverse_directory import TraverseDirectory
from paths import Paths


def run():
    # sub_dir = 'liked'
    # sub_dir = 'liked_redownloaded'
    sub_dir = 'most_music_redownloaded'
    # sub_dir = 'most_music'

    file_path = os.path.join(Paths.MUSIC, sub_dir)
    output_file_path = os.path.join(file_path, 'all_songs.txt')

    print_files_in_directory(file_path, output_file_path)


def print_files_in_directory(file_path, output_file_path):
    file_lists = FileListsStructured()
    file_lists.populate_lists_recursively(file_path)
    file_lists.write_lists_to_file(output_file_path)


class FileListsStructured(object):

    def __init__(self):
        self.dir_list = []
        self.file_dict = {}

    def get_sorted_list_for_dir(self, dir_name):
        return sorted(
            self.file_dict.get(dir_name, []),
            key=lambda x: x.lower()
        )

    def populate_lists_recursively(self, file_path):
        directory_lister = TraverseDirectoryLister(self)
        directory_lister.iterate_files_recursively(file_path, lazy=True)

    def write_lists_to_file(self, output_file_path):

        with open(output_file_path, 'w') as write_file:
    
            # write_file.write("Generated by " + os.path.realpath(__file__) + "\n")
            for dir_name in self.dir_list:
                write_file.write('--- ' + dir_name + '\n')
    
                for file_name in self.get_sorted_list_for_dir(dir_name):
                    if should_write_to_file(file_name):
                        try:
                            write_file.write(file_name + '\n')
                        except UnicodeEncodeError as e:
                            exit(f'ERROR writing {file_name}\n{e}')
    
                write_file.write('')


def should_write_to_file(file_name):
    title, extension = file_name.rsplit('.', 1)
    self.extensions[extension] = extensions.get(extension, 0) + 1
    if extension.lower() not in ['jpg', 'txt']:
        return True
    return False


class TraverseDirectoryLister(TraverseDirectory):

    def __init__(self, fsl):
        self.fsl = fsl

    def handle_dir(self, file_name, directory, full_path):
        self.fsl.dir_list.append(full_path)
        if full_path in self.file_dict:
            raise Exception("oh no " + full_path)
        self.fsl.file_dict[full_path] = []
        return True

    def handle_file(self, file_name, directory, full_path):
        self.fsl.file_dict[directory].append(full_path)
        return True


if __name__ == '__main__':
    run()
